name: Matrix Demo

on:
    push:
        branches:
            - main
            - dev

jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operating-system: [ubuntu-20.04, windows-latest, ubuntu-latest]
                include:
                    - node-version: 18
                      operating-system: ubuntu-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get the code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
