name: Matrix Demo

on:
    push:
        branches:
            - main
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
